name: Discord Commit Notifier

on:
  push:
    branches-ignore: 
      - 'main'
    
  workflow_dispatch:

jobs:
  notifier:
    runs-on: ubuntu-latest
    steps:
      - uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD }}
          title: "New commit on backend"
          color: 0xf58216
